import os
import numpy as np
import pandas as pd

from pathlib import Path
from scipy.interpolate import griddata
from scipy.spatial import cKDTree

from .... import utils
from ....gis import PointFileIO, XYZFormatSpec


class BathyMaker:
    """
    A class for preprocessing bathymetry data.

    1) 1D mode:
       - Reads an XYZ point cloud (topo-bathymetry).
       - Reads the 1D grid generated by GridMaker (x_profile.grd).
       - Uses the planar line defined by (start_xy, end_xy) to build a
         1D bathymetric profile aligned with the XBeach 1D grid.
       - Writes a .dep file (single column of depths) and an optional CSV
         with the extracted profile.

    2) 1D mode (file-based):
       - Reads a 2-column (x, z) profile from file.
       - Interpolates z to match a .grd file.
       - Writes corresponding .dep file.

    3) 2D mode (xyz2asc):
       - Converts bathymetry data from XYZ format to ESRI ASCII Grid format.

    Parameters
    ----------
    init : object
        Project initialization object. Must provide:
        - init.dict_folders["input"]: input directory.
        - init.dict_folders["run"]  : run directory.    
    filename : str, optional
        Default name of the .dep file to be written in the run folder.
        Default is "bed.dep".

    Attributes
    ----------
    init : object
        Reference to the project initialization object.
    filename : str
        Default .dep filename (e.g. "bed.dep") used by methods
        when no output name is explicitly provided.
    """

    def __init__(self, init, output_filename: str = "bed.dep"):
        self.init = init
        self.output_filename = output_filename
        self._bathy_dict = None

    @property
    def metadata(self):
        """
        Returns the metadata dictionary generated by the last bathymetry processing method.

        This dictionary contains key-value pairs relevant to the bathymetry file(s) created
        during preprocessing, such as file paths and names. The specific contents depend on
        the method used (e.g. `convert_xyz2asc`).

        Returns
        -------
        dict or None
            A dictionary with bathymetry metadata if available, otherwise None.
        """
        return self._bathy_dict

    def build_z_from_bathy(self,geometry_object):
        pass

        # if isinstance(geometry_object, ProfileAxis):
        #     pass # profile interpolator - ProfileInterpolator(xyz,profileAxis)
        # else:
        #         raise TypeError("Invalid geometry object. Must be a ProfileAxis")
    

    def build_z_from_existing_profile(self, xz_filepath):
        # read xz_filepath
        # entity with two columns (pd.DataFrame)
        # compute distance along profile (s) (last_record - first record)

        # compare length profile(profileAxis) with length of xz_filepath, round to one decimal.
        # 

        # if lengt_profileaxis == length xz_filepath:
            # write .dep file with z values from xz_filepath with interpolation
        # elif length_profileaxis < length xz_filepath:
            # trim length xz_filepath to length of profileAxis and write .dep file with z values from xz_filepath with interpolation
        # else:
            # raise Error

        pass


    def fill_bathy_section(self) -> None:
        """
        Add/edit bathymetry-related information in the XBeach params file.

        This is a thin wrapper around utils.fill_files.

        Parameters
        ----------
        dict_data : dict
            Mapping of parameter names to values, to be written into
            the file 'params.txt' in the run folder.
        """
        print("\n*** Adding/Editing bathymetry information in params file ***\n")
        params_path = os.path.join(self.init.dict_folders["run"], "params.txt")
        utils.fill_files(params_path, self._bathy_dict)
    
    def load_existing_dep(self, dep_filename):
        # read dep_filepath and store in self._bathy_dict
        pass