import os
import glob
import numpy as np
import pandas as pd

from scipy.interpolate import griddata
from scipy.spatial import cKDTree

from .. import utils


class BathyMaker:
    """
    Bathymetry pre-processing class for XBeach.

    This class provides two main workflows:

    1) 1D mode (recommended):
       - Reads an XYZ point cloud (topo-bathymetry).
       - Reads the 1D grid generated by GridMaker (x_profile.grd).
       - Uses the planar line defined by (start_xy, end_xy) to build a
         1D bathymetric profile aligned with the XBeach 1D grid.
       - Writes a .dep file (single row of depths) and an optional CSV
         with the extracted profile.

    2) 2D legacy mode (xyz2asc):
       - Interpolates XYZ bathymetry onto a regular 2D grid.

    Parameters
    ----------
    init : object
        Project initialization object. Must provide:
        - init.dict_folders["input"]: input directory (ending with '/').
        - init.dict_folders["run"]  : run directory (ending with '/').
    filename : str, optional
        Default name of the .dep file to be written in the run folder.
        Default is "bed.dep".

    Attributes
    ----------
    init : object
        Reference to the initialization object.
    filename : str
        Default .dep filename (e.g. "bed.dep") to be used in methods
        when output filename is not explicitly provided.
    """

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------
    def __init__(self, init, filename: str = "bed.dep", *args, **kwargs):
        self.init = init
        self.filename = filename

    # ------------------------------------------------------------------
    # Generic XYZ reader
    # ------------------------------------------------------------------
    @staticmethod
    def read_xyz_file(xyz_path: str) -> pd.DataFrame:
        """
        Read an XYZ point cloud file (topobathymetry) with robust parsing.

        The function:
        - Assumes at least 3 numeric columns: X, Y, Z.
        - Automatically drops non-numeric rows (e.g. header lines).
        - Renames the first three columns to ["X", "Y", "Z"].

        Parameters
        ----------
        xyz_path : str
            Path to an XYZ-like file. It can be whitespace-separated or
            CSV; this routine uses a whitespace delimiter and no header,
            which works for typical XYZ files. For CSV with commas, it is
            recommended to pass a pre-cleaned file.

        Returns
        -------
        df : pandas.DataFrame
            DataFrame with numeric columns ["X", "Y", "Z"].
        """
        df = pd.read_csv(
            xyz_path,
            delim_whitespace=True,
            header=None,
            comment="#",
            engine="python",
        )

        # Keep only first three columns
        df = df.iloc[:, :3]

        # Convert to numeric and drop non-finite values
        for col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
        df = df.dropna()

        df.columns = ["X", "Y", "Z"]
        return df

    # ------------------------------------------------------------------
    # 1D profile builder using GridMaker's x_profile.grd
    # ------------------------------------------------------------------
    def build_1d_profile_from_grid(
        self,
        xyz_filename: str,
        start_xy,
        end_xy,
        corridor_width: float = 500.0,
        xyz_is_depth: bool = False,
        x_grd_name: str = "x_profile.grd",
        dep_name: str | None = None,
        profile_csv_name: str = "profile_xz.csv",
    ) -> pd.DataFrame:
        """
        Build a 1D bathymetric profile aligned with GridMaker's 1D grid.

        This method is designed to work with the 1D configuration of
        GridMaker, where `x_profile.grd` is a 1-column file containing
        along-profile distances (in meters) from 0 to L:

            0
            dx1
            dx1 + dx2
            ...
            L

        The along-profile distances are projected along the straight line
        defined by (start_xy, end_xy), and a nearest-neighbor search
        (KDTree) is used to sample the bathymetric depth from the XYZ
        point cloud at each profile location.

        Parameters
        ----------
        xyz_filename : str
            Name of the XYZ file containing the scattered topo-bathymetry
            points. The file is searched in init.dict_folders["input"].
        start_xy : tuple(float, float)
            Planar coordinates (X, Y) of the profile origin, in the same
            CRS as the XYZ file (e.g. UTM).
        end_xy : tuple(float, float)
            Planar coordinates (X, Y) of the profile end point. This
            should be the final endpoint used by GridMaker (e.g.
            GridMaker.final_end_xy), so that the geometric line is
            consistent with the 1D grid.
        corridor_width : float, optional
            Half-width of the corridor (in meters) around the profile
            line used to pre-filter XYZ points before building the KDTree.
            Larger values increase robustness but cost; smaller values
            may fail if the cloud is sparse. Default is 500.0 m.
        xyz_is_depth : bool, optional
            If False (default), Z is assumed to be elevation (+up) and
            is converted to depth (+down) as depth = -Z.
            If True, Z is assumed to be depth (+down) already.
        x_grd_name : str, optional
            Name of the 1D grid file written by GridMaker (relative to
            the run folder). Default is "x_profile.grd".
        dep_name : str, optional
            Name of the .dep output file (stored in the run folder). If
            None, self.filename is used. The file is written as a single
            row of depths in XBeach 1D format.
        profile_csv_name : str, optional
            Name of the CSV file written in the run folder, containing
            the extracted 1D profile. Default is "profile_xz.csv".

        Returns
        -------
        profile_df : pandas.DataFrame
            DataFrame with columns:
            - 's_m' : float
                Along-profile distance from the origin [m] (values read
                from x_profile.grd).
            - 'X' : float
                Planar X coordinate of the profile point.
            - 'Y' : float
                Planar Y coordinate of the profile point.
            - 'z_m' : float
                Depth (+down) at each along-profile position.

        Notes
        -----
        - The .dep file is written as a single row of depths (z_m) with
          format '%.3f'. This matches the 1D XBeach `depfile` format.
        - The profile geometry (direction) is defined solely by start_xy
          and end_xy; the distances used for sampling are taken from the
          grid file x_profile.grd, so the number of points and spacing
          are exactly aligned with GridMaker's 1D grid.
        """

        # --------------------------------------------------------------
        # 1. Resolve file paths
        # --------------------------------------------------------------
        input_folder = self.init.dict_folders["input"]
        run_folder = self.init.dict_folders["run"]

        xyz_path = os.path.join(input_folder, xyz_filename)
        if not os.path.isfile(xyz_path):
            raise FileNotFoundError(f"XYZ file not found: {xyz_path}")

        x_grd_path = os.path.join(run_folder, x_grd_name)
        if not os.path.isfile(x_grd_path):
            raise FileNotFoundError(f"1D grid file not found: {x_grd_path}")

        # Output names
        if dep_name is None:
            dep_name = self.filename
        dep_path = os.path.join(run_folder, dep_name)

        profile_csv_path = os.path.join(run_folder, profile_csv_name)

        # --------------------------------------------------------------
        # 2. Read XYZ cloud
        # --------------------------------------------------------------
        df_xyz = self.read_xyz_file(xyz_path)
        X = df_xyz["X"].values.astype(float)
        Y = df_xyz["Y"].values.astype(float)
        Z = df_xyz["Z"].values.astype(float)

        # Convert Z to depth (+down)
        if xyz_is_depth:
            depth = Z
        else:
            depth = -Z

        # --------------------------------------------------------------
        # 3. Read along-profile distances from x_profile.grd
        # --------------------------------------------------------------
        s_query = np.loadtxt(x_grd_path).astype(float).ravel()

        if s_query.ndim != 1 or s_query.size < 2:
            raise ValueError(
                "x_profile.grd must be a 1D column with at least two points."
            )

        # Profile length is defined by the last distance
        L = float(s_query[-1])

        # --------------------------------------------------------------
        # 4. Define profile geometry in planar coordinates
        # --------------------------------------------------------------
        start = np.array(start_xy, dtype=float)
        end = np.array(end_xy, dtype=float)
        vec = end - start
        L_geom = float(np.hypot(vec[0], vec[1]))

        if L_geom == 0.0:
            raise ValueError(
                "start_xy and end_xy are identical; profile length is zero."
            )

        # Unit vector along the profile line
        u = vec / L_geom

        # Profile coordinates in planar space at each s_query position
        Xq = start[0] + u[0] * s_query
        Yq = start[1] + u[1] * s_query

        # --------------------------------------------------------------
        # 5. Pre-filter XYZ cloud within a corridor around the profile
        #    to reduce KDTree cost.
        # --------------------------------------------------------------
        points = np.column_stack((X, Y))
        rel = points - start

        # Projection along the line (coordinate s along profile)
        s_points = rel @ u

        # Signed perpendicular distance from the line (2D cross product)
        n_points_perp = rel[:, 0] * u[1] - rel[:, 1] * u[0]

        # Mask points within extended interval and within corridor_width
        mask = (
            (s_points >= -corridor_width)
            & (s_points <= L + corridor_width)
            & (np.abs(n_points_perp) <= corridor_width)
        )

        X_f = X[mask]
        Y_f = Y[mask]
        D_f = depth[mask]

        if X_f.size < 10:
            raise ValueError(
                "Too few points inside the profile corridor. "
                "Increase corridor_width or check XYZ coverage."
            )

        # --------------------------------------------------------------
        # 6. Build KDTree and query nearest neighbors
        # --------------------------------------------------------------
        tree = cKDTree(np.column_stack((X_f, Y_f)))
        _, idx = tree.query(np.column_stack((Xq, Yq)), k=1)

        depth_profile = D_f[idx]

        # --------------------------------------------------------------
        # 7. Build output DataFrame
        # --------------------------------------------------------------
        profile_df = pd.DataFrame(
            {
                "s_m": s_query,        # along-profile distance [m]
                "X": Xq,               # planar X coordinate
                "Y": Yq,               # planar Y coordinate
                "z_m": depth_profile,  # depth (+down)
            }
        )

        # --------------------------------------------------------------
        # 8. Write .dep file (single row of depths)
        # --------------------------------------------------------------
        np.savetxt(dep_path, depth_profile.reshape(-1, 1), fmt="%.3f")
        print(f"1D bathymetry written to: {dep_path}")

        # --------------------------------------------------------------
        # 9. Write CSV profile
        # --------------------------------------------------------------
        profile_df.to_csv(profile_csv_path, index=False)
        print(f"Profile CSV written to: {profile_csv_path}")

        return profile_df

    # ------------------------------------------------------------------
    # 2D legacy mode (kept for compatibility)
    # ------------------------------------------------------------------
    def xyz2asc(self, dx_bat: float, nodata_value: float) -> dict:
        """
        Interpolate XYZ bathymetry onto a regular 2D grid and write an
        ESRI ASC-like .dep file.

        This method is a legacy 2D workflow and does not interact with
        GridMaker's 1D profile. It is kept here for compatibility with
        older 2D XBeach setups.

        Parameters
        ----------
        dx_bat : float
            Grid spacing in both x and y directions [m].
        nodata_value : float
            Value to use for cells where interpolation fails (NaN).

        Returns
        -------
        meta : dict
            Dictionary with metadata about the generated grid:
            - 'depfilepath' : str
            - 'x_bot'       : int (number of cells in x-direction)
            - 'y_bot'       : int (number of cells in y-direction)
            - 'spacing_x'   : float
            - 'spacing_y'   : float
            - 'nelayerfilepath' : str (placeholder)
        """
        input_folder = self.init.dict_folders["input"]
        run_folder = self.init.dict_folders["run"]

        # Try to find a bathymetry CSV automatically
        candidates = glob.glob(os.path.join(input_folder, "bathy*.csv"))
        if not candidates:
            raise FileNotFoundError(
                f"No bathy*.csv file found in input folder: {input_folder}"
            )
        bathy_xyz_path = candidates[0]

        ascfile = os.path.join(run_folder, self.filename)
        df_xyz = pd.read_csv(bathy_xyz_path)

        # Compute grid extents (note: depends on original column naming)
        min_x, max_x = df_xyz["Y"].min(), df_xyz["Y"].max()
        min_y, max_y = df_xyz["X"].min(), df_xyz["X"].max()

        # Compute number of grid cells (simple integer division)
        nx_bathy = int((min_x - max_x) / dx_bat)
        ny_bathy = int((max_y - min_y) / dx_bat)

        # Generate grid with data
        xi, yi = np.mgrid[
            min_x : max_x : (nx_bathy + 1) * 1j, min_y : max_y : (ny_bathy + 1) * 1j
        ]

        # Interpolate bathymetry (linear by default)
        zi = griddata(
            (df_xyz["Y"], df_xyz["X"]),
            df_xyz["Z"],
            (xi, yi),
            method="linear",
        )

        # Replace NaNs with nodata
        zi[np.isnan(zi)] = nodata_value

        # Simple clipping example (can be adapted)
        zi[zi < -10] = -1

        # Flip and transpose to match expected orientation
        zi = np.fliplr(zi)
        zi = zi.T

        # Write ASCII file
        zi_str = np.where(zi == nodata_value, str(nodata_value), np.round(zi, 3))
        np.savetxt(ascfile, zi_str, fmt="%8.6s", delimiter=" ")
        print(f"2D bathymetry written to: {ascfile}")

        meta = {
            "depfilepath": self.filename,
            "x_bot": nx_bathy,
            "y_bot": ny_bathy,
            "spacing_x": dx_bat,
            "spacing_y": dx_bat,
            "nelayerfilepath": "ne_layer.dep",
        }
        # Cast all values to string for convenience in params filling
        return {k: str(v) for k, v in meta.items()}

    # ------------------------------------------------------------------
    # Utilities related to params.txt
    # ------------------------------------------------------------------
    def fill_bathy_section(self, dict_data: dict) -> None:
        """
        Add/edit bathymetry-related information in the XBeach params file.

        This is a thin wrapper around utils.fill_files.

        Parameters
        ----------
        dict_data : dict
            Mapping of parameter names to values, to be written into
            the file 'params.txt' in the run folder.
        """
        print("\n*** Adding/Editing bathymetry information in params file ***\n")
        params_path = os.path.join(self.init.dict_folders["run"], "params.txt")
        utils.fill_files(params_path, dict_data)


