import os
import glob
import numpy as np
import pandas as pd

from scipy.interpolate import griddata
from scipy.spatial import cKDTree

from .. import utils


class BathyMaker:
    """
    A class for preprocessing bathymetry data.

    1) 1D mode:
       - Reads an XYZ point cloud (topo-bathymetry).
       - Reads the 1D grid generated by GridMaker (x_profile.grd).
       - Uses the planar line defined by (start_xy, end_xy) to build a
         1D bathymetric profile aligned with the XBeach 1D grid.
       - Writes a .dep file (single column of depths) and an optional CSV
         with the extracted profile.

    2) 1D mode (file-based):
       - Reads a 2-column (x, z) profile from file.
       - Interpolates z to match a .grd file.
       - Writes corresponding .dep file.

    3) 2D mode (xyz2asc):
       - Converts bathymetry data from XYZ format to ESRI ASCII Grid format.

    Parameters
    ----------
    init : object
        Project initialization object. Must provide:
        - init.dict_folders["input"]: input directory.
        - init.dict_folders["run"]  : run directory.    
    filename : str, optional
        Default name of the .dep file to be written in the run folder.
        Default is "bed.dep".

    Attributes
    ----------
    init : object
        Reference to the project initialization object.
    filename : str
        Default .dep filename (e.g. "bed.dep") used by methods
        when no output name is explicitly provided.
    """

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------
    def __init__(self, init, filename: str = "bed.dep"):
        self.init = init
        self.filename = filename
    # ------------------------------------------------------------------
    # Generic XYZ reader
    # ------------------------------------------------------------------
    @staticmethod
    def read_xyz_file(xyz_path: str) -> pd.DataFrame:
        """
        Read an XYZ point cloud file (topobathymetry).

        This method:

        - Assumes at least 3 numeric columns: X, Y, Z.
        - Automatically drops non-numeric rows (e.g. header lines).
        - Renames the first three columns to ["X", "Y", "Z"].

        Parameters
        ----------
        xyz_path : str
            Path to an XYZ-like file. It can be whitespace-separated or
            CSV; this routine uses a whitespace delimiter and no header,
            which works for typical XYZ files. For CSV with commas, it is
            recommended to pass a pre-cleaned file.

        Returns
        -------
        df : pandas.DataFrame
            DataFrame with numeric columns ["X", "Y", "Z"].
        """
        df = pd.read_csv(
            xyz_path,
            delim_whitespace=True,
            header=None,
            comment="#",
            engine="python",
        )

        # Keep only first three columns
        df = df.iloc[:, :3]

        # Convert to numeric and drop non-finite values
        for col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
        df = df.dropna()

        df.columns = ["X", "Y", "Z"]
        return df

    # ------------------------------------------------------------------
    # 1D profile builder using GridMaker's x_profile.grd
    # ------------------------------------------------------------------
    def build_1d_profile_from_grid(
        self,
        xyz_filename: str,
        start_xy : tuple[float, float],
        end_xy   : tuple[float, float],
        corridor_width: float = 500.0,
        xyz_is_depth: bool = False,
        x_grd_name: str = "x_profile.grd",
        dep_name: str | None = None,
        profile_csv_name: str = "profile_xz.csv",
    ) -> pd.DataFrame:
        """
        Build a 1D bathymetric profile aligned with GridMaker's 1D grid.

        This method is designed to work with the 1D configuration of
        GridMaker, where `x_profile.grd` is a 1-column file containing
        along-profile distances (in meters) from 0 to L:

            0
            dx1
            dx1 + dx2
            ...
            L

        The along-profile distances are projected along the straight line
        defined by (start_xy, end_xy), and a nearest-neighbor search
        (KDTree) is used to sample the bathymetric depth from the XYZ
        point cloud at each profile location.

        Parameters
        ----------
        xyz_filename : str
            Name of the XYZ file containing the scattered topo-bathymetry
            points. The file is searched in init.dict_folders["input"].
        start_xy : tuple(float, float)
            Planar coordinates (X, Y) of the profile origin, in the same
            CRS as the XYZ file (e.g. UTM).
        end_xy : tuple(float, float)
            Planar coordinates (X, Y) of the profile end point. This
            should be the final endpoint used by GridMaker (e.g.
            GridMaker.final_end_xy), so that the geometric line is
            consistent with the 1D grid.
        corridor_width : float, optional
            Half-width of the corridor (in meters) around the profile
            line used to pre-filter XYZ points before building the KDTree.
            Larger values increase robustness but cost; smaller values
            may fail if the cloud is sparse. Default is 500.0 m.
        xyz_is_depth : bool, optional
            If False (default), Z is assumed to be elevation (+up) and
            is converted to depth (+down) as depth = -Z.
            If True, Z is assumed to be depth (+down) already.
        x_grd_name : str, optional
            Name of the 1D grid file written by GridMaker (relative to
            the run folder). Default is "x_profile.grd".
        dep_name : str, optional
            Name of the .dep output file (stored in the run folder). If
            None, self.filename is used. The file is written as a single
            row of depths in XBeach 1D format.
        profile_csv_name : str, optional
            Name of the CSV file written in the run folder, containing
            the extracted 1D profile. Default is "profile_xz.csv".

        Returns
        -------
        profile_df : pandas.DataFrame
            DataFrame with columns:
            - 's_m' : float
                Along-profile distance from the origin [m] (values read
                from x_profile.grd).
            - 'X' : float
                Planar X coordinate of the profile point.
            - 'Y' : float
                Planar Y coordinate of the profile point.
            - 'z_m' : float
                Depth (+down) at each along-profile position.

        Notes
        -----
        - The .dep file is written as a single row of depths (z_m) with
          format '%.3f'. This matches the 1D XBeach `depfile` format.
        - The profile geometry (direction) is defined solely by start_xy
          and end_xy; the distances used for sampling are taken from the
          grid file x_profile.grd, so the number of points and spacing
          are exactly aligned with GridMaker's 1D grid.
        """

        # --------------------------------------------------------------
        # 1. Resolve file paths
        # --------------------------------------------------------------
        input_folder = self.init.dict_folders["input"]
        run_folder = self.init.dict_folders["run"]

        xyz_path = os.path.join(input_folder, xyz_filename)
        if not os.path.isfile(xyz_path):
            raise FileNotFoundError(f"XYZ file not found: {xyz_path}")

        x_grd_path = os.path.join(run_folder, x_grd_name)
        if not os.path.isfile(x_grd_path):
            raise FileNotFoundError(f"1D grid file not found: {x_grd_path}")

        # Output names
        if dep_name is None:
            dep_name = self.filename
        dep_path = os.path.join(run_folder, dep_name)

        profile_csv_path = os.path.join(run_folder, profile_csv_name)

        # --------------------------------------------------------------
        # 2. Read XYZ cloud
        # --------------------------------------------------------------
        df_xyz = self.read_xyz_file(xyz_path)
        X = df_xyz["X"].values.astype(float)
        Y = df_xyz["Y"].values.astype(float)
        Z = df_xyz["Z"].values.astype(float)

        # Convert Z to depth (+down)
        if xyz_is_depth:
            depth = Z
        else:
            depth = -Z

        # --------------------------------------------------------------
        # 3. Read along-profile distances from x_profile.grd
        # --------------------------------------------------------------
        s_query = np.loadtxt(x_grd_path).astype(float).ravel()

        if s_query.ndim != 1 or s_query.size < 2:
            raise ValueError(
                "x_profile.grd must be a 1D column with at least two points."
            )

        # Profile length is defined by the last distance
        L = float(s_query[-1])

        # --------------------------------------------------------------
        # 4. Define profile geometry in planar coordinates
        # --------------------------------------------------------------
        start = np.array(start_xy, dtype=float)
        end = np.array(end_xy, dtype=float)
        vec = end - start
        L_geom = float(np.hypot(vec[0], vec[1]))

        if L_geom == 0.0:
            raise ValueError(
                "start_xy and end_xy are identical; profile length is zero."
            )

        # Unit vector along the profile line
        u = vec / L_geom

        # Profile coordinates in planar space at each s_query position
        Xq = start[0] + u[0] * s_query
        Yq = start[1] + u[1] * s_query

        # --------------------------------------------------------------
        # 5. Pre-filter XYZ cloud within a corridor around the profile
        #    to reduce KDTree cost.
        # --------------------------------------------------------------
        points = np.column_stack((X, Y))
        rel = points - start

        # Projection along the line (coordinate s along profile)
        s_points = rel @ u

        # Signed perpendicular distance from the line (2D cross product)
        n_points_perp = rel[:, 0] * u[1] - rel[:, 1] * u[0]

        # Mask points within extended interval and within corridor_width
        mask = (
            (s_points >= -corridor_width)
            & (s_points <= L + corridor_width)
            & (np.abs(n_points_perp) <= corridor_width)
        )

        X_f = X[mask]
        Y_f = Y[mask]
        D_f = depth[mask]

        if X_f.size < 10:
            raise ValueError(
                "Too few points inside the profile corridor. "
                "Increase corridor_width or check XYZ coverage."
            )

        # --------------------------------------------------------------
        # 6. Build KDTree and query nearest neighbors
        # --------------------------------------------------------------
        tree = cKDTree(np.column_stack((X_f, Y_f)))
        _, idx = tree.query(np.column_stack((Xq, Yq)), k=1)

        depth_profile = D_f[idx]

        # --------------------------------------------------------------
        # 7. Build output DataFrame
        # --------------------------------------------------------------
        profile_df = pd.DataFrame(
            {
                "s_m": s_query,        # along-profile distance [m]
                "X": Xq,               # planar X coordinate
                "Y": Yq,               # planar Y coordinate
                "z_m": depth_profile,  # depth (+down)
            }
        )

        # --------------------------------------------------------------
        # 8. Write .dep file (single row of depths)
        # --------------------------------------------------------------
        np.savetxt(dep_path, depth_profile.reshape(-1, 1), fmt="%.3f")
        print(f"1D bathymetry written to: {dep_path}")

        # --------------------------------------------------------------
        # 9. Write CSV profile
        # --------------------------------------------------------------
        profile_df.to_csv(profile_csv_path, index=False)
        print(f"Profile CSV written to: {profile_csv_path}")

        return profile_df
    
    def build_1d_profile_from_file(
        self,
        profile_filename: str,
        x_grd_name: str = "x_profile.grd",
        dep_name: str | None = None,
    ) -> pd.DataFrame:
        """
        Interpolates a (x, z) profile from a text file to match the XBeach .grd,
        and saves a .dep file in the run folder.

        Parameters
        ----------
        profile_filename : str
            Name of the 2-column text file (x, z) located in input folder.
        x_grd_name : str, optional
            Name of the .grd file located in the run folder.
        dep_name : str, optional
            Output .dep file name. Default is self.filename.

        Returns
        -------
        pd.DataFrame
            DataFrame with 'x_grd' and 'z_interp' columns.
        """

        input_folder = self.init.dict_folders["input"]
        run_folder = self.init.dict_folders["run"]

        profile_path = os.path.join(input_folder, profile_filename)
        x_grd_path = os.path.join(run_folder, x_grd_name)

        if not os.path.isfile(profile_path):
            raise FileNotFoundError(f"Profile file not found: {profile_path}")
        if not os.path.isfile(x_grd_path):
            raise FileNotFoundError(f"GRD file not found: {x_grd_path}")

        # Read file (x,z) 
        profile = pd.read_csv(profile_path, sep=",", header=0)  
        profile.columns = ["x", "z"]  

        profile["x"] = pd.to_numeric(profile["x"], errors="coerce")
        profile["z"] = pd.to_numeric(profile["z"], errors="coerce")
        profile = profile.dropna()

        profile = profile.sort_values("x")


        # Read x_profile.grd
        x_grd = np.loadtxt(x_grd_path).astype(float).ravel()

        # Interpolation
        z_interp = np.interp(x_grd, profile["x"], profile["z"])

        # Save as .dep file
        if dep_name is None:
            dep_name = self.filename
        dep_path = os.path.join(run_folder, dep_name)
        np.savetxt(dep_path, z_interp.reshape(-1, 1), fmt="%.3f")
        print(f"Interpolated 1D .dep written to: {dep_path}")

        return pd.DataFrame({"x_grd": x_grd, "z_interp": z_interp})
        

    # ------------------------------------------------------------------
    # 2D mode 
    # ------------------------------------------------------------------
    def xyz2asc(self):
        """
        Converts bathymetry data from XYZ format to ESRI ASCII Grid format.

        Notes
        -----
        - The input file is automatically searched in
        ``init.dict_folders["input"]`` using the pattern ``TopoBathy*.csv``.
        - The CSV file is assumed to represent a regular grid and must
        contain three columns corresponding to X, Y, and Z.
        - Missing values (NaN) are written as empty fields in the DEP file,
        following the legacy format.

        Returns
        -------
        dict
            Dictionary with metadata of the generated bathymetry:
            - 'depfilepath' : str
            - 'nelayerfilepath' : str
        """
        bathy_xyz_path = glob.glob(f'{self.init.dict_folders["input"]}TopoBathy*.csv')[0]
        ascfile = f'{self.init.dict_folders["run"]}{self.filename}.dep'
        # ascfile_ne_ones = f'{self.dict_folders["run"]}ne_layer_ones.dep'
        df_xyz = pd.read_csv(bathy_xyz_path,header=0,names=['X','Y','Z'])
        df_xyz = df_xyz.drop_duplicates()

        grid = df_xyz.pivot_table(index="Y", columns="X", values="Z")
        grid = grid.sort_index(ascending=False)
        grid = grid[grid.columns[::-1]]

        arr = grid.values.astype(float)
        out = np.empty(arr.shape, dtype='U16')
        mask = np.isnan(arr)
        out[~mask] = np.char.mod('%3.5f', arr[~mask])
        out[mask] = ''
        np.savetxt(ascfile, out, fmt='%s', delimiter=' ')


        # zi_ones=np.ones(zi.shape)
        # np.savetxt(ascfile_ne_ones, zi_ones, fmt='%8s', delimiter=' ')

        print('File %s saved successfuly.' % ascfile)

        dict_asc={'depfilepath':f'{self.filename}.dep','nelayerfilepath':'ne_layer.dep'}
        for key,value in dict_asc.items():
            dict_asc[key]=str(value)
        return dict_asc


    # ------------------------------------------------------------------

    # def profile2asc(self):
    #     dat_files=glob.glob(f'{self.dict_folders["input"]}*.dat')
    #     bathy_file = [file for file in dat_files if 'Perfil_0' in file][0]
    #     print(f'Using bathymetry file: {bathy_file}')
    #     data=np.loadtxt(bathy_file)
    #     ascfile = f'{self.dict_folders["run"]}{self.filename}.dep'
    #     np.savetxt(ascfile,data[:,3][::-1],fmt='%f')
    #     print('File %s saved successfuly.' % ascfile)

    #     dict_asc={'depfilepath':f'{self.filename}.dep'}

    #     ne_layer=np.ones(data[:,1].shape)*1
    #     np.savetxt(f'{self.dict_folders["run"]}nelayer.dep',ne_layer,fmt='%f')

    #     for key,value in dict_asc.items():
    #         dict_asc[key]=str(value)
            
    #     return dict_asc


    # def xyz2asc(self,dx_bat,nodata_value):
    #     """
    #     Converts bathymetry data from XYZ format to ESRI ASCII Grid format.

    #     Args:
    #         nodata_value (float): The value to replace NaN values in the grid.

    #     Returns:
    #         dict: A dictionary containing the metadata of the generated grid.
    #     """
    #     bathy_xyz_path = glob.glob(f'{self.dict_folders["input"]}*.csv')[0]
    #     ascfile = f'{self.dict_folders["run"]}{self.filename}.dep'
    #     ascfile_ne_ones = f'{self.dict_folders["run"]}ne_layer_ones.dep'
    #     np.set_printoptions(formatter={'float_kind':'{:f}'.format})
    #     # Read bathymetry file
    #     longitude,latitude,z = np.loadtxt(bathy_xyz_path, delimiter=',', unpack=True, skiprows=1)

    #     # print(longitude,latitude,z)

    #     # Load the shapefile
    #     sf = shapefile.Reader(f'{self.dict_folders["input"]}Modelo_2D.shp')

    #     # Extract the shapes and records
    #     shapes = sf.shapes()
    #     records = sf.records()

    #     # Assuming the shapefile contains only one rectangle
    #     shape = shapes[0]

    #     # Extract the bounding box (min_lon, min_lat, max_lon, max_lat)
    #     min_lon, min_lat, max_lon, max_lat = shape.bbox

    #     # Print the bounding box
    #     # print(f'Bounding box: min_lon={min_lon}, min_lat={min_lat}, max_lon={max_lon}, max_lat={max_lat}')

    #     min_longitude = int(np.ceil(min_lon / 50) * 50)-50
    #     max_longitude = int(np.floor(max_lon / 50) * 50)+50
    #     min_latitude = int(np.ceil(min_lat / 50) * 50)-50
    #     max_latitude = int(np.floor(max_lat / 50) * 50)+50   

    #     ymax=max_longitude
    #     ymin=min_longitude
    #     xmin=max_latitude
    #     xmax=min_latitude

    #     nx_bathy = int((xmin - xmax)/dx_bat)
    #     ny_bathy = int((ymax - ymin)/dx_bat)
    #     # # Generate grid with data
    #     xi, yi = np.mgrid[xmin:xmax:(nx_bathy+1)*1j, ymin:ymax:(ny_bathy+1)*1j]  # Caution

    #     # # Interpolate bathymetry. Method can be 'linear', 'nearest' or 'cubic'
    #     zi = griddata((latitude,longitude), z, (xi, yi), method='linear')
    #     # # Change Nans for values
    #     zi[np.isnan(zi)] = nodata_value
    #     # Flip array in the left/right direction
    #     # zi = np.fliplr(zi)
    #     # Transpose it
    #     zi = zi.T
    #     # Write ESRI ASCII Grid file
    #     zi_str = np.where(zi == nodata_value, str(nodata_value), np.round(zi, 3))

    #     zi_ones=np.ones(zi.shape)
    #     np.savetxt(ascfile, zi_str, fmt='%8s', delimiter=' ')
    #     np.savetxt(ascfile_ne_ones, zi_ones, fmt='%8s', delimiter=' ')

    #     print('File %s saved successfuly.' % ascfile)

    #     dict_asc={'depfilepath':f'{self.filename}.dep','x_bot':nx_bathy,'y_bot':ny_bathy,'spacing_x':dx_bat,'spacing_y':dx_bat,
    #               'nelayerfilepath':'ne_layer.dep'}
    #     for key,value in dict_asc.items():
    #         dict_asc[key]=str(value)
    #     return dict_asc
    
    # def read_dry_index(self):
    #     index_dry = glob.glob(f'{self.dict_folders["input"]}indexes_dry_points.txt')[0]
    #     points= np.loadtxt(index_dry)
    #     xi,yi=points[:,1],points[:,2]
    #     ne_layer_ones=np.loadtxt(f'{self.dict_folders["run"]}ne_layer_ones.dep')
    #     for idx_x,idx_y in zip(xi,yi):
    #         ne_layer_ones[int(idx_y),-int(idx_x)]=0
    #     # ne_layer_ones = np.fliplr(ne_layer_ones)
    #     # Transpose it
    #     # ne_layer_ones = ne_layer_ones.T
    #     ascfile_ne = f'{self.dict_folders["run"]}ne_layer.dep'
    #     np.savetxt(ascfile_ne, ne_layer_ones, fmt='%8s', delimiter=' ')
    #     print('File %s saved successfuly.' % ascfile_ne)

    # def bathy_from_DELFT3D(self,filename_dep,filename_nedep):
    #     os.system(f'cp {self.dict_folders["input"]}{filename_dep}.dep {self.dict_folders["run"]}')
    #     os.system(f'cp {self.dict_folders["input"]}{filename_nedep}.dep {self.dict_folders["run"]}')

    #     dict_asc={'depfilepath':f'{filename_dep}.dep','model_origin':'delft3d',
    #               'nelayerfilepath':f'{filename_nedep}.dep'}
    #     return dict_asc

    def fill_bathy_section(self, dict_data: dict) -> None:
        """
        Add/edit bathymetry-related information in the XBeach params file.

        This is a thin wrapper around utils.fill_files.

        Parameters
        ----------
        dict_data : dict
            Mapping of parameter names to values, to be written into
            the file 'params.txt' in the run folder.
        """
        print("\n*** Adding/Editing bathymetry information in params file ***\n")
        params_path = os.path.join(self.init.dict_folders["run"], "params.txt")
        utils.fill_files(params_path, dict_data)